# Generated by Django 4.0.4 on 2024-06-07 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_customer_firstname_alter_customer_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdocument',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.customer'),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.documentset'),
        ),
    ]
